# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# compile CXX with /usr/bin/c++
CXX_DEFINES = -DBOOST_ALL_NO_LIB -DBOOST_ATOMIC_DYN_LINK -DBOOST_CHRONO_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_LOG_DYN_LINK -DBOOST_LOG_SETUP_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DGUIDANCE -DINIT_PP -DLNS_GROUP_SIZE=10 -DOBJECTIVE=4 -DRELAX=100 -DROBOT_RUNNERS -DSWAP -Dpy_driver_EXPORTS

CXX_INCLUDES = -I/home/lyh/MAPF_PIED_MDDR_RESEARCH/implementation_binding_evidence/baseline_selection_20260929/OnlineGGO/Guided-PIBT/guided-pibt/inc -I/home/lyh/MAPF_PIED_MDDR_RESEARCH/implementation_binding_evidence/baseline_selection_20260929/OnlineGGO/Guided-PIBT/guided-pibt/traffic_mapf -I/usr/include/eigen3 -I/home/lyh/MAPF_PIED_MDDR_RESEARCH/implementation_binding_evidence/baseline_selection_20260929/OnlineGGO/third_party/MiniDNN/include -isystem /home/lyh/MAPF_PIED_MDDR_RESEARCH/implementation_binding_evidence/baseline_selection_20260929/OnlineGGO/Guided-PIBT/guided-pibt/pybind11/include -isystem /usr/include/python3.10

CXX_FLAGS =  -fno-lto -O3 -DNDEBUG -fPIC -fvisibility=hidden -flto -fno-fat-lto-objects

