"""Write reports from retained full-set results, without selecting new experiments."""
from fractions import Fraction as Q
from collections import Counter
import json
import runner
P=runner.HERE
def get(name):return json.loads((P/name).read_text()) if (P/name).exists() else None
def main():
 s=get('SUMMARY.json');rr=get('RESULTS.json');pairs=get('PAIR_REACHABILITY.json');coverage=get('BRANCHES_BEFORE_OUTCOMES.json');probes=[r for r in rr if r['policy'].startswith(('cf_','pair_'))];skip=get('SKIP_LIFETIMES.json');root=get('ROOT_VALUE_SPACE.json');neg=get('NEGATIVE_CONTROLS.json');matched=get('MATCHED_TAIL_AUDIT.json');aud=get('AUDIT_ALL.json');archives=get('RAW_ARCHIVE_MANIFEST.json')
 both=sum(r['vs_condition']['task_gain']>0 and r['vs_whole_WAIT']['task_gain']>0 for r in probes);overpi=sum(f['best_registered_probe_tasks']>f['condition_tasks'] for f in s['families']);gain2=sum(p['vs_first_only']['task_gain']>0 for p in pairs)
 lines=['# R11: public opportunity and finite two-intervention value space','',f"Completed {s['native_episodes']} native runs across four new TRAIN families: 8 whole-run references, {s['single_branches']} complete one-intervention branches, and {s['pair_branches']} fixed public two-intervention arms; {s['failed']} execution failures. Of the registered probe arms, {both} improve whole-task throughput strictly over both original condition pi0 and whole-run WAIT. The finite probe set improves throughput over pi0 in {overpi}/4 families. A second intervention improves throughput over its matched first-only branch in {gain2}/{len(pairs)} arms. These are TRAIN mechanism diagnostics, not a fitted model, held-out result, or an optimality claim.",'','| Family (map / scenario / offset / seed) | pi0 tasks | whole WAIT | best single | best pair | arms with task gain over both |','|---|---:|---:|---:|---:|---:|']
 for f in s['families']:lines.append(f"| {f['world']} | {f['condition_tasks']} | {f['whole_WAIT_tasks']} | {f['best_single_tasks']} | {f['best_pair_tasks']} | {f['task_improving_arms_vs_both']} |")
 totals=dict(condition=sum(f['condition_tasks'] for f in s['families']),whole_WAIT=sum(f['whole_WAIT_tasks'] for f in s['families']),best_probe_per_family=sum(f['best_registered_probe_tasks'] for f in s['families']),reference_envelope=sum(max(f['condition_tasks'],f['whole_WAIT_tasks']) for f in s['families']))
 lines += ['',f"Selecting each family's best registered probe retrospectively gives {totals['best_probe_per_family']} tasks, versus {totals['condition']} for fixed condition and {totals['whole_WAIT']} for fixed whole WAIT. This equals the {totals['reference_envelope']}-task envelope obtained by choosing the better reference separately per family. Thus one of eight single opportunities exposes a real +1 TRAIN task over pi0, and conditional policy selection may have learning potential. The data show no extra throughput beyond that reference envelope. The familywise retrospective selector has not been learned or evaluated on new families."]
 lines += ['', 'All task counts use the entire FIFO through H=128. The secondary objective is J=tasks−T/16385, where T is the sum of restricted completion times for the fixed first four tasks per agent (unfinished tasks contribute 128). RESULTS retains the summed interval bounds; a robust gain requires the lower bound of the J difference to exceed 0. Small midpoint differences whose interval contains 0 are unresolved. Arms and candidates are correlated interventions within a family, not independent replicates.','', '## Registered coverage and public action semantics','',f"The run cap was 140; deterministic public selection produced 94 runs and was not filled to the cap. The condition baselines selected {s['selected_opportunities']} opportunities, the first early (spent 0–7) and late (spent 8–15) slots per family. Exactly {s['selected_two_candidate_opportunities']} selected opportunity has two visible candidates. There are {s['selected_coupled_opportunities']} selected coupled opportunities: no candidate simultaneously blocked multiple distinct current heads and no blocked-head claim had multiple owners in the sampled condition strata. Two visible candidates, multi-owner/multi-head blocking, and two interventions are separate notions. This experiment does not validate combined blocking.", '', 'Each selected opportunity includes current WAIT and QUERY/SKIP for every visible candidate. SKIP binds the full (agent, move occurrence) pair and removes only that occurrence until accepted, delivered normal END. Current WAIT installs no skip state. Both forced actions and the live continuation use public state; the original physics, ownership/certificate rules, author World3 bridge, controller and count budget are pinned. Public task lineage is updated only after accepted END and successor-head revelation. No private future END or unseen FIFO task is used to select either intervention.','', 'Each early/late anchor fixes six first WAIT/QUERY/SKIP × second QUERY/SKIP policies. The second event is the earliest eligible public decision with budget and a different complete identity. The early anchor also fixes three successor-triggered second-SKIP policies. Targets rank by exact public condition score, then agent and action ID, including zero scores in these forced diagnostics. No second point or action is selected from outcomes. All registered pair arms and empty coverage strata are retained.','', '| Second trigger | Registered arms | Second action actually reached | Positive task gain over same-first single | Robust J gain over same-first single |','|---|---:|---:|---:|---:|']
 for t,x in s['pairs_by_trigger'].items():lines.append(f"| {t} | {x['arms']} | {x['second_reached']} | {sum(v for k,v in x['task_gain_vs_first_only'].items() if int(k)>0)} | {x['robust_J_improvements_vs_first_only']} |")
 unresolved=[p for p in pairs if not p['second_reached']];lines += ['', f"Unreached second actions: {len(unresolved)}. These mean no qualifying public trigger occurred before the count budget was exhausted or H was reached; they are not successful forced WAIT actions. PAIR_REACHABILITY records budget exhaustion, public descendant heads and the actual first/second identities. Unreached branches are checked against their matched first-only full public/physical trajectory. A public descendant being revealed alone does not establish a visible legal query opportunity.", '', '## Secondary service effects and persistence','', '| Family | Robust J-improving probe arms vs pi0 | Robust J-improving probe arms vs both references |','|---|---:|---:|']
 for f in s['families']:lines.append(f"| {f['world']} | {f['robust_J_improving_arms_vs_condition']} | {f['robust_J_improving_arms_vs_both']} |")
 best_rows=[]
 lines += ['', 'The following maximum-J choices include both references and are retrospective descriptions of this finite set. They are not deployed selectors; ties use the policy name only to choose a reproducible representative. T gains are fixed-first-four restricted-time sums in seconds, not per-task averages.', '', '| Family | Retrospective maximum-J arm | task gain vs pi0 / WAIT | T gain interval vs pi0 | T gain interval vs WAIT |','|---|---|---:|---:|---:|']
 for world in [f['world'] for f in s['families']]:
  r=min([r for r in rr if r['world']==world],key=lambda r:(-Q(r['J_lower'])-Q(r['J_upper']),r['policy']));best_rows.append(r)
  show=lambda d:'['+format(float(Q(d['time_gain_lower'])),'.6f')+', '+format(float(Q(d['time_gain_upper'])),'.6f')+']'
  lines.append(f"| {world} | {r['policy']} | {r['vs_condition']['task_gain']} / {r['vs_whole_WAIT']['task_gain']} | {show(r['vs_condition'])} | {show(r['vs_whole_WAIT'])} |")
 losses=[p for p in pairs if p['vs_first_only']['task_gain']<0]
 if losses:lines += ['', 'Negative effects are retained: '+'; '.join(f"{p['world']} / {p['policy']} changes throughput by {p['vs_first_only']['task_gain']} relative to its same-first single and pi0; the second legal action is {p['second_action']} on {p['second_move']} at opportunity {p['second_opportunity']} with remaining budget {p['remaining_at_second']}" for p in losses)+'.']
 (P/'SECONDARY_VALUE_SPACE.json').write_text(json.dumps(dict(selection='retrospective maximum interval midpoint J; lexical policy tie; all references included',task_totals=totals,families=best_rows,negative_pair_effects=losses),indent=2)+'\n')
 lines += ['',f"The eight complete single opportunities include {s['single_opportunities_task_headroom_vs_condition']} with task headroom over pi0 and {s['single_opportunities_task_headroom_vs_both']} over both references. OPPORTUNITY_VALUE_SPACE preserves every zero-space opportunity. Full task-service record equality and gained/omitted query identities are in RESULTS; fixed-first-four timing is reported separately from whole-FIFO throughput."]
 if skip:lines += ['',f"Across all arms, {skip['installed']} SKIP occurrences were installed; {skip['cleared_at_accepted_END']} cleared immediately after the matching accepted normal END. Their original identities reappeared in raw candidate visibility {skip['raw_reappearances']} times while remaining masked. {skip['with_later_same_agent_visible']} installations have a later distinct occurrence of the same agent visible; {skip['with_new_queried_occurrences']} lie in branches querying identities absent from that family's condition run. SKIP_LIFETIMES reports per-installation budget at installation/clear and the next actual QUERY. This proves retained count budget and changed allocation where observed; it does not price production CPU or network cost."]
 if skip:lines += ['',f"The maximum simultaneous skip set is {skip['max_simultaneous_skip_bindings']} identities, reached in {skip['episodes_with_two_simultaneous_skips']} arm. All {len(probes)} intervention arms finish with {sorted({r['queries'] for r in probes})} queries, while whole WAIT uses zero. The retained budget is eventually spent; these results concern changed allocation and service, not reduced total query counts."]
 lines += ['', '## Validation, failures and provenance','',f"Independent Decimal physics/controller/owner/FIFO and exact rational policy audit: {'PASS '+str(aud['executions'])+' episodes' if aud else 'pending final aggregation'}. Prefix and fixed-tail replay: {'PASS; '+str(matched['same_action_full_trajectory_controls'])+' same-action or unreached full-trajectory controls' if matched else 'pending'}. Negative controls: {str(len(neg['cases']))+' rejected' if neg else 'pending'}. Root-owned independent raw value-space/lineage/score/trigger audit: {'PASS '+str(root['runs'])+' runs' if root else 'pending root completion'}. ROOT_RECONCILIATION compares all 94 independently computed throughput, timing interval, J and reachability results. These independent checks include candidate lists before/after masking, exact scoring/ties, no forced QUERY without a legal target, actual budget consumption, and accepted-END-only skip clearance.", '', 'Before scientific runs, the initial random scenario 1 offsets were rejected because the file has only 461 rows. The preserved preflight documents the correction to separately pinned official scenario 2 offsets 0/16, with seeds and experiment cap unchanged. The first guessed ZIP URL returned 404; the correct [official MAPF benchmark archive](https://movingai.com/benchmarks/mapf/random-32-32-10.map-scen-random.zip) was then downloaded. Both the failed attempt and final input hashes are retained. The two empty families use original scenario 1 offsets 448/464. Family keys include map, scenario identity, offset and seed. NOVELTY_PREFLIGHT checks prior registered seeds/task IDs and scenario row groups.', '', 'An auditor-only missing re import was corrected before any probe outcomes or pair audits; AUDITOR_IMPORT_FIX_BEFORE_PROBES records both hashes and the approved audit-supervisor restart. Registered native/runner/pipeline/contract and experiment behavior were unchanged. This exception is explicit in final source-pin verification. R7–R10 frozen artifacts and original production headers remain pinned. No model was trained and no result-selected sample or horizon extension was run.']
 if archives:lines += ['',f"Raw records are preserved exactly once in {len(archives['archives'])} compressed archives ({archives['raw_member_count']} files), each below 45 MB, with verified member SHA256. Build/runs/audits caches are excluded from the publication whitelist; archive and frozen source hashes permit reconstruction with the pinned external author dependencies."]
 lines += ['', '## Consequence for the next learning target','']
 if both==0:lines += ['The +1 task over fixed pi0 is small but real TRAIN headroom, so these results do not rule out learning a conditional choice among condition, WAIT and persistent SKIP. They do not establish that public features can generalize that choice: the familywise best throughput merely reaches the condition/WAIT reference envelope, and no model or held-out family was tested. A next learning study should preregister that modest selection target and compare with both fixed references and explicit public selectors; increasing model size alone is not supported. Robust service-time effects under a throughput constraint offer a separate target. Keep the zero-space and unreachable opportunities, and do not recast finite diagnostic maxima as deployed performance.']
 else:lines += ['The registered set exposes finite whole-task headroom over both references. This is an opportunity-space observation, not evidence that a learned rule can select those actions on new families. A subsequent model would require a new preregistered split and deployable public target, keeping zero and unreachable opportunities and testing throughput against both references.']
 census=s['whole_run_visible_census'];idx=lines.index('## Secondary service effects and persistence');with_public=sum(bool(p['successor_evidence']['public_descendants_before_budget_exhaustion']) for p in unresolved);lines[idx:idx]=[f"Among the {len(unresolved)} unreached successor arms, {with_public} had public descendant heads revealed before budget exhaustion but still no legal successor-trigger candidate; {len(unresolved)-with_public} had none revealed before exhaustion. Later revelation alone cannot recover already spent budget. This describes observed public availability rather than attributing the result to a private future event.",'',f"Across all 94 full trajectories (including repeated references), {census['multi_candidate_decisions']} public decisions in {census['episodes_with_multi_candidates']} arms have multiple candidates; {census['coupled_blocking_decisions']} decisions in {census['episodes_with_coupled_blocking']} arms meet the registered coupled-blocking predicate. This is a descriptive repeated-trajectory census, not additional independent coverage.",'']
 (P/'REPORT.md').write_text('\n'.join(lines)+'\n')
 (P/'HANDOFF.md').write_text(f"# R11 query handoff\n\n{len(rr)} complete TRAIN-only native arms; no training or TEST experiment. Read REPORT.md and SUMMARY.json first. RESULTS.json/CSV includes whole-FIFO service counts and interval-valued fixed-first-four objective; PAIR_REACHABILITY and OPPORTUNITY_VALUE_SPACE retain unavailable/zero-space cases. Registered cap 140 produced 94 arms by public rules, with no refill.\n\nEntry scripts: pipeline.py register/base/probes; audit_all.py; verify_matched_tail.py; summarize.py; skip_lifetimes.py; negative_controls.py; archive.py; write_report.py; publish_manifest.py. Do not rerun frozen scientific outputs in place. Root owns root_value_space.py / ROOT_VALUE_SPACE.json, all Git and publication. Source pins, input provenance, import-only auditor exception and raw archive hashes are included in the whitelist. Production COST/AUTH, external-baseline victory, held-out learning and combined-blocking validation are not established.\n\nFamilywise retrospective best gives {totals['best_probe_per_family']} tasks vs fixed pi0 {totals['condition']} and whole WAIT {totals['whole_WAIT']}, equal to the {totals['reference_envelope']}-task familywise reference envelope. This preserves modest conditional-selection learning potential while providing no trained or held-out improvement evidence. Per-family task gains strictly over both references: {both} registered probe arms. Positive task effects of second intervention over its same-first single: {gain2}/{len(pairs)}. Pair/candidate arms are not independent statistical samples; there are four new TRAIN families.\n")
 print('REPORT/HANDOFF written',flush=True)
if __name__=='__main__':main()
