# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# compile CXX with /usr/bin/c++
CXX_DEFINES = -DBOOST_ALL_NO_LIB -DBOOST_ATOMIC_DYN_LINK -DBOOST_CHRONO_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_LOG_DYN_LINK -DBOOST_LOG_SETUP_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DFOCAL_SEARCH=2 -DGUIDANCE -DGUIDANCE_LNS=10 -DINIT_PP -DLNS_GROUP_SIZE=10 -DOBJECTIVE=1 -DRELAX=100 -DROBOT_RUNNERS

CXX_INCLUDES = -I/home/lyh/MAPF_PIED_MDDR_RESEARCH/implementation_binding_evidence/baseline_selection_20260929/gpibt_seeded_trace_successor/guided-pibt/inc -I/home/lyh/MAPF_PIED_MDDR_RESEARCH/implementation_binding_evidence/baseline_selection_20260929/gpibt_seeded_trace_successor/guided-pibt/traffic_mapf

CXX_FLAGS = -O3 -DNDEBUG

