"""Write descriptive reports for the complete frozen R12 experiment."""
from fractions import Fraction as Q
from collections import Counter
import json
import runner
P=runner.HERE
def get(name):return json.loads((P/name).read_text()) if (P/name).exists() else None
def fmt(x):return format(float(Q(x)),'.6f')
def main():
 s=get('SUMMARY.json');rr=get('RESULTS.json');test=[r for r in rr if r['split']=='test'];models=get('MODELS_FROZEN_BEFORE_TEST.json');full=s['totals']['full'];audit=get('AUDIT_ALL.json');deploy=get('DEPLOYMENT_AUDIT.json');neg=get('NEGATIVE_CONTROLS.json');skip=get('SKIP_LIFETIMES.json');arc=get('RAW_ARCHIVE_MANIFEST.json');root=get('ROOT_MACRO_AUDIT.json');mentor=get('MENTOR_MODEL_AUDIT.json');reg=get('REGISTRATION.json')
 margin='infinity' if s['shared_margin'] is None else s['shared_margin']
 def status(d):return 'PASS' if d and d.get('passed') is True else ('incomplete' if d else 'pending')
 lines=['# R12: learned conditional macro selection under paired budgets','',f"Completed {s['native_episodes']} native episodes: 96 complete TRAIN/CAL macro branches and 56 frozen TEST deployments, with {s['failed']} execution failures. The full learned selector serves {full['tasks']} tasks across the eight TEST family/budget contexts: task differences are {full['vs_condition']['tasks']:+d} versus condition, {full['vs_WAIT']['tasks']:+d} versus whole WAIT, and {full['vs_budget_lookup']['tasks']:+d} versus the TRAIN budget lookup. These eight contexts come from four independent TEST families with paired B8/B16 settings; they are not eight independent replications.", '', '| TEST policy | Tasks across both budgets | Queries | Δtasks vs condition | Δtasks vs WAIT | Δtasks vs TRAIN lookup | Chosen macro counts |','|---|---:|---:|---:|---:|---:|---|']
 for policy,t in s['totals'].items():lines.append(f"| {policy} | {t['tasks']} | {t['queries']} | {t['vs_condition']['tasks']:+d} | {t['vs_WAIT']['tasks']:+d} | {t['vs_budget_lookup']['tasks']:+d} | {json.dumps(t['macro_choices'],sort_keys=True)} |")
 lines += ['', 'All task counts cover the whole FIFO through H=128. Primary differences are reported per family and budget in RESULTS and aggregated within family in FAMILY_RESULTS. The secondary completion-time measure T is the restricted sum over each agent’s fixed first four FIFO tasks, with uncompleted tasks assigned 128; it is not the whole-FIFO task count. J=tasks−T/16385. Time and J comparisons retain rational lower/upper bounds; a robust improvement requires the lower difference bound to exceed zero.','', '## What was learned and actually deployed','',f"Six TRAIN families provide twelve paired budget contexts. For each of five alternatives to condition, the code fits a task-advantage head and a normalized time-advantage head. Full, selector-history-masked and selector-budget-masked variants yield 30 ridge heads in total (25 public features plus intercept, lambda 1, TRAIN-only scaling, per-budget weight 1/2, nine-decimal rational deployment coefficients). The tasks_only policy reuses the full task heads. CAL contains two independent families/four budget contexts and chooses a single shared activation margin: {margin}. The TRAIN-only budget lookup selects {s['TRAIN_budget_lookup']['8']} at B8 and {s['TRAIN_budget_lookup']['16']} at B16.", '', 'The selector runs once at the first legal public opportunity. Its inputs are the slotwise means of the original 24 public candidate features plus candidate_count/N; it receives no agent/task/map ID, seed, split or future state. It chooses one complete macro C, W, E, L, ED or LD. C is condition throughout; W is whole WAIT; E skips the early top public occurrence, L skips at the first opportunity after at least half the supplied query budget has been spent; ED/LD add a SKIP at the earliest later legal different complete occurrence. Both target ranks and trigger rules are fixed public functions. Between/after skips the original condition policy continues. The fixed macro interpreter used for TRAIN labels is the same one used after learned TEST selection. A single-intervention label is never redeployed repeatedly as though its tail were unchanged.', '', 'Total budget B is externally supplied, not learned. B8 and B16 use the same starts, task streams and ordinal execution errors within a family. The model is fitted to value the finite macros under the supplied budget. The selector-budget ablation masks slots 20/22/23 while retaining the actual hard budget and macro thresholds. Selector-history masks 10..17 while retaining public eligibility and the original history-aware condition tail. These are selector-feature ablations, not systems with no budget or no END history. tasks_only removes the time head at inference but shares full’s time-aware CAL threshold; it is not an independently time-blind calibrated algorithm.','', '| Ablation vs full | Macro-choice disagreements / 8 | Full service-sequence changes / 8 | Task difference |','|---|---:|---:|---:|']
 for policy,a in s['ablations'].items():lines.append(f"| {policy} | {a['macro_disagreements_vs_full']} | {a['service_changes_vs_full']} | {a['task_difference_vs_full']:+d} |")
 train_labels=get('TRAIN_CAL_LABELS.json');trained=[r for r in train_labels if r['split']=='train' and r['option']!='C' and r['features'] is not None];nonzero=sum(Q(r['task_target'])!=0 for r in trained)
 lines += ['',f"Among the {len(trained)} non-condition TRAIN macro labels with a legal gate, {nonzero} have nonzero task advantages; time labels are separately retained with their interval bounds."]
 lines += ['', '| TRAIN macro vs condition | Task-positive / zero / negative labels | Robust T gain / unresolved / loss |', '|---|---:|---:|']
 for option in ['W','E','L','ED','LD']:
  a=[r for r in trained if r['option']==option];pos=sum(Q(r['task_target'])>0 for r in a);zero=sum(Q(r['task_target'])==0 for r in a);neg_task=len(a)-pos-zero;tp=sum(Q(r['T_gain_lower'])>0 for r in a);tn=sum(Q(r['T_gain_upper'])<0 for r in a)
  lines.append(f"| {option} | {pos} / {zero} / {neg_task} | {tp} / {len(a)-tp-tn} / {tn} |")
 if s['shared_margin'] is None:
  lines += ['', 'The frozen CAL margin is infinity. All learned variants therefore execute condition even when their fitted scores differ. Their equal deployed choices and trajectories cannot identify the effect of history, budget features or the time head. The experiment has implemented and exercised fitting and exact inference, but it has not demonstrated learned conditional budget allocation on TEST.']
 lines += ['', '| Full CAL margin | Total tasks | Restricted T interval | Queries | Chosen macros |', '|---|---:|---:|---:|---|']
 for c in models['calibration']['grid']:
  lines.append(f"| {c['margin'] if c['margin'] is not None else 'infinity'} | {c['tasks']} | [{fmt(c['T_lower'])}, {fmt(c['T_upper'])}] | {c['queries']} | {json.dumps(dict(Counter(x['selected_option'] for x in c['selections'])),sort_keys=True)} |")
 lines += ['', 'CAL selects maximum total tasks first, then the interval-undominated restricted-time set, then fewer queries, then the larger margin. Thus the largest tied threshold may select infinity; this is a recorded calibration outcome, not a threshold changed after seeing TEST.']
 if nonzero==0:lines += ['', 'All TRAIN task-advantage targets are zero, so the fitted task heads are zero. Any learned preferences in this round come from completion-time heads; this is not evidence of learning a throughput-improvement relation. The tasks_only default to condition under the nonnegative shared margin is part of the measured ablation, not an independently discovered policy.']
 lines += ['', 'The counts distinguish running inference, choosing a different macro, and changing actual service. Identical ablation outcomes show no measured contribution in these contexts; they do not establish that the omitted information can never matter.', '', '## Per-context learned outcomes and completion-time value','', '| TEST family | B | Full option | Full tasks | Δtasks vs condition / WAIT / lookup | T gain vs condition interval | Queries | Actual / planned SKIPs |','|---|---:|---|---:|---:|---:|---:|---:|']
 for r in sorted([r for r in test if r['policy']=='full'],key=lambda r:(r['family_key'],r['budget'])):
  d=r['vs_condition'];lines.append(f"| {r['family_key']} | {r['budget']} | {r['selected_option'] or 'NO_GATE'} | {r['tasks']} | {d['tasks']:+d} / {r['vs_WAIT']['tasks']:+d} / {r['vs_budget_lookup']['tasks']:+d} | [{fmt(d['T_gain_lower'])}, {fmt(d['T_gain_upper'])}] | {r['queries']} | {r['actual_interventions']} / {r['requested_interventions']} |")
 lines += ['', '| Policy | T gain interval vs condition (sum over paired contexts) | Robust aggregate J gain vs condition | Actual SKIPs | Unreached planned SKIPs |','|---|---:|---:|---:|---:|']
 for policy,t in s['totals'].items():
  d=t['vs_condition'];lines.append(f"| {policy} | [{fmt(d['T_gain_lower'])}, {fmt(d['T_gain_upper'])}] | {d['robust_J_improvement']} | {t['interventions']} | {t['unreached_interventions']} |")
 from summarize import total,delta
 lines += ['', '| Supplied budget | TRAIN lookup macro | Tasks lookup / condition | Queries lookup / condition | Lookup T gain vs condition |', '|---|---|---:|---:|---:|']
 for b in [8,16]:
  lookup=total([r for r in test if r['budget']==b and r['policy']=='budget_lookup']);condition=total([r for r in test if r['budget']==b and r['policy']=='condition']);d=delta(lookup,condition)
  lines.append(f"| {b} | {s['TRAIN_budget_lookup'][str(b)]} | {lookup['tasks']} / {condition['tasks']} | {lookup['queries']} / {condition['queries']} | [{fmt(d['T_gain_lower'])}, {fmt(d['T_gain_upper'])}] |")
 lines += ['', 'At B16 the TRAIN-frozen LD lookup keeps 170 tasks, uses 52 queries versus condition’s 56, and reduces restricted T by [4.072604, 4.072940]. Its timing gain comes from random family 122302; the other three families have identical service records. Each empty family saves two queries. At B8 the TRAIN-frozen W lookup increases T by about 17.0089, so the aggregate lookup loses time despite its B16 gain. These are outcomes of the preregistered per-budget lookup, not gains attributable to the learned selector.', '', f"Full’s aggregate T gains are [{fmt(full['vs_WAIT']['T_gain_lower'])}, {fmt(full['vs_WAIT']['T_gain_upper'])}] versus WAIT and [{fmt(full['vs_budget_lookup']['T_gain_lower'])}, {fmt(full['vs_budget_lookup']['T_gain_upper'])}] versus lookup. Full executes condition in all eight contexts, so those gains belong to the original condition policy. Identical full/condition trajectories establish no actual service or timing difference; the displayed self-comparison interval width is numerical enclosure, not a measured effect."]
 lines += ['', 'The protocol retains any unreached late/second trigger in the denominator, using its realized full-tail outcome. In these 152 runs all 104 planned SKIPs were reached; no unavailable trigger was relabeled as a successful intervention. All task differences and negative timing outcomes are retained. The four-family pilot does not support broad advantage or combination-blocking claims.','', '## Original execution and verification','',f"The complete Move3/World3 block and the public history/feature construction are byte-identical to frozen R11. Changes are confined to actor macro selection/state/logging, the policy allow-list, a clock header for host timing, and runner budget/provenance binding. The original author planner, continuous controller, geometry, ownership, certified POSITION release, FIFO service and candidate eligibility remain pinned. Independent physics and exact macro replay: {'PASS '+str(audit['executions'])+' episodes' if audit else 'pending'}. Deployment/hash/time/prefix controls: {'PASS '+str(deploy['episodes'])+' episodes, '+str(deploy['same_macro_full_trajectory_controls'])+' same-macro full-trajectory comparisons' if deploy else 'pending'}. Negative controls: {str(len(neg['cases']))+' rejected' if neg else 'pending'}."]
 if skip:lines += ['',f"There were {skip['installed']} persistent SKIP installations; {skip['cleared_at_accepted_END']} cleared directly after their matching accepted normal END, with any horizon-censored lifetime retained. Masked identities reappeared in raw candidates {skip['raw_reappearances']} times without becoming visible. {skip['with_later_same_agent_visible']} installations have a later distinct occurrence of the same agent visible. Maximum simultaneous bindings: {skip['max_simultaneous_skip_bindings']}. Per-installation remaining budget and subsequent QUERY identities are preserved in SKIP_LIFETIMES."]
 inferred=[r['selector_scoring_ns'] for r in test if r['inference_calls']]
 lines += ['',f"TEST recorded {sum(r['inference_calls'] for r in test)} learned-selector calls. Host scoring/threshold-selection durations span {min(inferred) if inferred else 0}–{max(inferred) if inferred else 0} ns. The timer excludes candidate-feature and mean-feature construction, and is host metadata rather than physical completion time or production COST.", '',f"Root raw macro/prefix/deployment audit artifact: {status(root)}. Mentor independent label/refit/CAL/lookup audit artifact: {status(mentor)}. These audit files own their exact PASS criteria and limitations; their source and result hashes are part of the final publication whitelist.", '', 'Source, inputs and learning/calibration algorithms were frozen before TRAIN. Complete common public/physical prefixes were independently checked before fitting; identical mean features alone were not treated as equal states. TRAIN standardization, all raw/rounded coefficients, row bindings, labels and CAL grid outcomes are retained. Model/margin/lookup hashes and nanosecond start/end receipts link source freeze→96 TC outcomes→fit→model freeze→TEST. Every TEST input contains the exact frozen coefficients and control parameters; cached receipts are reusable only with matching input/model, executable, bridge/config, world/budget and raw hashes.', '', 'Pre-execution reviews identified a permissive cache binding and a missing complete-prefix fit prerequisite. Both were fixed before any scientific outcome. The initial registration is retained as ATTEMPT01; the explicit zero-run registration revision adds the prefix prerequisite and a predeclared zero-head/C fallback for the all-no-gate case. All 24 declared world/budget inputs remain fixed. The official empty scenario2 archive was newly pinned; random scenario2 was copied from frozen R11. Prior seeds/task identities and scenario row groups, free-space geometry and paired inputs were checked. No seed, option, budget or horizon was added after seeing outcomes.']
 if arc:lines += ['',f"Every raw record is archived once: {arc['raw_member_count']} members in {len(arc['archives'])} SHA-verified compressed files, each under 45 MB. Reproduction requires the pinned external author bridge, configuration and numerical dependencies; this is not a self-contained production release."]
 offline=get('OFFLINE_REPLAY_RECEIPT.json')
 if offline:lines += ['', f"Independent offline archive replay: {status(offline)}. The root audit reconstructed all 152 episodes from eight compressed archives in a fresh temporary directory and reproduced its complete result JSON exactly, without invoking the native simulator. See OFFLINE_REPLAY_RECEIPT.json, ROOT_TEST_RESULTS.json and ROOT_MODEL_DIAGNOSTICS.json; the diagnostic analysis did not refit or retune the frozen policy."]
 if (P/'ASTRA_POSTEXEC.md').exists() and (P/'MENTOR_POSTEXEC.md').exists():lines += ['', 'The independent implementation and scientific assessments are retained in [ASTRA_POSTEXEC.md](ASTRA_POSTEXEC.md) and [MENTOR_POSTEXEC.md](MENTOR_POSTEXEC.md). [ROOT_CONCLUSION.md](ROOT_CONCLUSION.md) records the root review and the [figure caption](figures/CAPTION.md) defines the plotted quantities.']
 lines += ['', '## Interpretation','']
 if all(full['vs_'+ref]['tasks']>0 for ref in ['condition','WAIT','budget_lookup']):lines += ['The frozen full selector increases task throughput over all three aggregate references in this pilot. Per-family losses, interval-valued timing and ablations determine the limits of that observation; a larger newly registered family set is needed before claiming generalization beyond this small test.']
 else:lines += ['R12 completes matched-macro training, exact native inference and frozen deployment, but shows no learned throughput or allocation gain on TEST. All 60 non-condition TRAIN task labels are zero, and CAL selects infinity; every learned variant then executes condition. The finite macro set contains some completion-time signal and the TRAIN-frozen B16 LD lookup improves time and saves queries on TEST, while its B8 W lookup loses time. These limited findings do not identify a useful learned conditional choice rule. A follow-up needs newly registered public opportunities with informative task or timing labels, while preserving complete-macro tails, real budget variation and zero-space outcomes.']
 (P/'REPORT.md').write_text('\n'.join(lines)+'\n')
 (P/'HANDOFF.md').write_text(f"# R12 query handoff\n\n152 native episodes:96 complete TRAIN/CAL macros +56 TEST; four independent TEST families paired at B8/B16. No production code, old frozen directory, entry README, manuscript or Git change by the implementation agent.\n\nStart with REPORT.md, SUMMARY.json and FAMILY_RESULTS.json. Full TEST task differences versus condition/WAIT/TRAIN budget lookup: {full['vs_condition']['tasks']:+d}/{full['vs_WAIT']['tasks']:+d}/{full['vs_budget_lookup']['tasks']:+d}. Shared CAL margin={margin}; TRAIN lookup={s['TRAIN_budget_lookup']}. All negative and unreached cases remain in RESULTS.\n\nCore entry: pipeline.py register/tc/test; learn.py performs prefix prerequisite, TRAIN fits, full-only shared CAL margin and model freeze. The protocol and data are fixed; do not rerun scientific outputs in place. audit_all.py, verify_execution.py, negative_controls.py, skip_lifetimes.py and independently owned root/mentor audits verify the evidence. Source/model phase hashes and native ns timestamps are linked.\n\nRoot owns Git/publication. Use PUBLICATION_MEMBERS.json and FROZEN_MANIFEST.json; raw records appear only in hashed archive parts. Holdout has four independent families, not56 replicates. Selector ablations preserve original condition tails and actual budget; tasks_only shares the full CAL threshold. Supplied total B is external, and measured host scoring time excludes feature construction.\n")
 print('REPORT/HANDOFF written',flush=True)
if __name__=='__main__':main()
